name: mantidimaging-nightly
channels:
  - mantidimaging/label/unstable
  - conda-forge
  - ccpi
  - algotom
  - https://software.repos.intel.com/python/conda/
# Dependencies that can be installed with conda should be in conda/meta.yaml
dependencies:
  - mantidimaging>=2.5.0
  - conda-forge::numexpr # https://github.com/mantidproject/mantidimaging/issues/1774
